- name: Devops course info
  hosts: local
  connection: local
  vars: 
    number: 15
  tasks:
  - name: print the number ris greather than 10
    ansible.builtin.debug:
        msg: "print the given number {{ number }}"
    when: number > 25

