- name: play1
  hosts: local
  connection: local
  tasks: 
  - name: play1
    ansible.builtin.debug:
      msg: "hello from play1"

- name: play2
  hosts: local
  connection: local
  tasks:
  - name: play2
    ansible.builtin.debug:
      msg: "hello form play2"
      

