- name: install softwares
  hosts: web
  become: yes
  tasks:
  - name: installing packages from loops are
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - gcc
    - mysql
    - git
    - zip


